### ISSUE TITLE
[Translation] Doc：deploy-aws

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-community-loc-cn#27]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：deploy-aws 的翻译
文档链接：https://crowdin.com/translate/apache-pulsar/12/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by dislazy** [comment]
mark

**Comment by dislazy** [comment]
Translation completed
@Tango2018cc @JipeiWang
