### ISSUE TITLE
[Translation] Doc：txn-why

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-community-loc-cn#57]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：txn-why 的部分翻译
文档链接：https://crowdin.com/translate/apache-pulsar/5320/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by lzhpo** [comment]
mark

**Comment by tuhaihe** [comment]
@lzhpo 感谢高质量翻译，已 Review 完成。有问题可以在 Crowdin 中评论或者重开本 Issue 🤝。
