### ISSUE TITLE
[Translation] Doc：txn-what

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-community-loc-cn#58]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：txn-what 的部分翻译
文档链接：https://crowdin.com/translate/apache-pulsar/5322/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by lzhpo** [comment]
mark

**Comment by tuhaihe** [comment]
@lzhpo 感谢高质量翻译，已 Review 完成，里面部分翻译留了评论，可以参考。如有问题，欢迎 Crowdin 中留言，或者重新打开该 Issue 🤝。
