### ISSUE TITLE
[Translation] Doc：txn-use

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-community-loc-cn#59]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：txn-use 的部分翻译
文档链接：https://crowdin.com/translate/apache-pulsar/5324/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by lzhpo** [comment]
mark

**Comment by tuhaihe** [comment]
@lzhpo hi 已 Review 完，感谢贡献，修订了多个不太妥当的译法，请参考。欢迎讨论 🤝 如有问题，可随时重开该 issue。

**Comment by Tango2018cc** [comment]
@all-contributors , please add @lzhpo  as the contributor for translation
