### ISSUE TITLE
[Translation] Doc：txn-how

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-community-loc-cn#60]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：txn-how 的部分翻译
文档链接：https://crowdin.com/translate/apache-pulsar/5326/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by safaf11** [comment]
认领翻译

**Comment by tuhaihe** [comment]
@safaf11 你好，已Review完成，感谢贡献👍🏻
有些部分翻译可多注意原文格式如换行符、强调符号、序号等等，都可以保留。如有问题，可保持交流。
